### ISSUE TITLE
Setup pytest

### ISSUE THREAD

**Issue by maxnordlund** [Karspexet/Karspexet#2]
Instead of using the builtin [`unittest`](https://docs.python.org/3.5/library/unittest.html) from the standard library, we want to use the nicer and more extendable [`pytest`](http://pytest.org/latest/). The latter has support for linting, behaviour (gherkin), running in parallel, coverage among others. But more importantly it runs all of these different types of test using a single tool, which makes it much easier to use.

To play nicely with others, and make most CI happy, we should also configure [`tox`](https://tox.readthedocs.org/en/latest/) to run our test suite. The logical extension after that is to setup some sort of CI.

---
- [x] Install and configure [`pytest`](http://pytest.org/latest/)
- [x] Install and configure [`tox`](https://tox.readthedocs.org/en/latest/). This should be simple as [`pytest`](http://pytest.org/latest/) is compatible, and has docs for it.
- [ ] Configure/write example for
  - [ ] Unit tests. This is the most important, the rest is more like sugar on top.
  - [ ] Integration test, by that I mean something running an browser. Not sure if gherkin is good or bad here?
  - [ ] Linting, using pep8, flakes and friends. I think there's an combined tool/pytest plugin as well, which we should probably use.
- [x] Setup CI
  - [x] Test runner, like semaphore or circle
  - [x] Coverage, maybe code climate if they support python/django and is free for OSS?
  - [x] Hound, to get instant feedback on style issues?

**Comment by Frost** [comment]
* https://codeclimate.com/github/Karspexet/Karspexet

**Comment by Frost** [comment]
See #5 for CI test runner. It still needs some configuring, but it's at least there.

**Comment by Frost** [comment]
[Hound](https://houndci.com/configuration#python) does seem to have support for python. :)

**Comment by maxnordlund** [comment]
Nice, very nice. Now we just need to configure them a bit.

**Comment by Frost** [comment]
#7 contains basic py.test configuration.

**Comment by Frost** [comment]
The python-configuration for hound uses flake8 btw, so i guess we have that covered as well.

**Comment by maxnordlund** [comment]
Yes, but we should also make sure to find a plugin for pytest to do the same. Just to make it easier for ourselves. I _really_ like the idea of running a single command and get both unit/E2E/lint tests run and presented in a uniform way.

**Comment by maxnordlund** [comment]
CodeClimate also uses it, through [radon](https://github.com/rubik/radon)<sup>[1](https://flake8.readthedocs.org/en/latest/extensions.html#existing-extensions)</sup>.

**Comment by Frost** [comment]
That might be an idea. I have a flake8 plugin in emacs, so I'm good :)

**Comment by maxnordlund** [comment]
We need a `setup.cfg` I think

**Comment by Frost** [comment]
For what?

**Comment by maxnordlund** [comment]
It's the place where (most) tools read their config. So instead of having a bunch of `.*` files, we only have one with different sections. It's in `.ini` format.

**Comment by Frost** [comment]
Oh, that's handy. Also, another difference from what I'm used to in other languages.

**Comment by maxnordlund** [comment]
Actually I think we can just have a `tox.ini`, since both flake8 and pytest reads from it as well. Very handy.

**Comment by Frost** [comment]
tox.ini is in place.

**Comment by maxnordlund** [comment]
I think we need the `setup.cfg` back, since we're killing tox in #15

**Comment by maxnordlund** [comment]
Also, didn't you @Frost  get the unit _and_ cucumber/integration tests to run? Then I think this is pretty much done.

**Comment by Frost** [comment]
@maxnordlund I did, in some branch locally. There's not much to test though, but @strokirk and I will get to that.

I got some kind of selenium-based tests working at least.

**Comment by maxnordlund** [comment]
@Frost I think this can be marked as done, right?

**Comment by Frost** [comment]
Definitely.
