### ISSUE TITLE
Upgrade Django

### ISSUE THREAD

**Issue by strokirk** [Karspexet/Karspexet#277]
Vi använder för närvarande Django 1.11, vilket är en relativt gammal version vid detta laget. Det vore bra att uppgradera, för att nya personer som bidrar till projektet enklare skall hitta relevant dokumentation online när de googlar.

**Comment by Frost** [comment]
Det här är en jättebra idé! Jag har försökt kolla på det litegrann tidigare, men det verkar vara en hel del saker som behöver fixas, och jag vet inte om det är några andra dependencies som också behöver uppdateras.

Har du koll på det, eller ska vi försöka skapa ett sånt "Project" här på GitHub för att hålla koll på det?

**Comment by strokirk** [comment]
Om det är många saker som skall fixas kan ett Github-projekt säkert fungera bra. Då kan man koppla relevanta PRs till det. Jag fixar!

**Comment by Frost** [comment]
Sen kan det ju vara en idé att uppgradera en version åt gången, tills vi kör senaste stabila django. Det hade varit riktigt trevligt att komma hela vägen till 3.0, tycker jag, men det lär ju inte vara gjort i en handvändning, direkt.

**Comment by strokirk** [comment]
Detta är nu i hamn! Krävde även en uppgradering av Postgres från 9.1 till något mer modernt, vilket var en resa i sig.
