### ISSUE TITLE
Add data model

### ISSUE THREAD

**Issue by maxnordlund** [Karspexet/Karspexet#3]
Before we do this, we should really sit down and draw some schemas, but once we know what we need we can start writing the basic model class files.

This issue serves as a reminder, but also as a place to write our thoughts/discussions down. This will, in time, make it easier to understand why things are like they are, hopefully.

**Comment by maxnordlund** [comment]
Now that there's a [Trello board][1], and we've talked about this, there is a much better plan in place.

[1]: https://trello.com/b/8hVLIEtl/nya-systemet-python-django

**Comment by maxnordlund** [comment]
Ping @Frost did you make a pretty graph by any chance? I don't know if we should keep this issue open or just close it in favour of having the discussion IRL and just write it down in an document. (That could live on the [wiki](https://github.com/Karspexet/Karspexet/wiki))

**Comment by Frost** [comment]
No fancy graph yet, but I did write everything down. I'll close this.
